extends AudioStreamPlayer2D

func _ready():
    pass

var U00 = preload("res://Sound Effect - Gladiaturtles/fight music.wav")
var U01 = preload("res://Sounds/01.wav")
var U02 = preload("res://Sounds/02.wav")
var U03 = preload("res://Sounds/03.wav")
var U04 = preload("res://Sounds/04.wav")
var U05 = preload("res://Sounds/05.wav")
var U06 = preload("res://Sounds/06.wav")
var U07 = preload("res://Sounds/07.wav")
var U08 = preload("res://Sounds/08.wav")
var U09 = preload("res://Sounds/09.wav")
var U10 = preload("res://Sounds/10.wav")
var U11 = preload("res://Sounds/11.wav")
var U12 = preload("res://Sounds/12.wav")
var U13 = preload("res://Sounds/13.wav")
var U14 = preload("res://Sounds/14.wav")
var U15 = preload("res://Sounds/15.wav")
var U16 = preload("res://Sounds/16.wav")
var U17 = preload("res://Sounds/17.wav")
var U18 = preload("res://Sounds/18.wav")
var U19 = preload("res://Sounds/19, 21.wav")
var U20 = preload("res://Sounds/20.wav")
var U22 = preload("res://Sounds/22.wav")
var U23 = preload("res://Sounds/23.wav")
var U24 = preload("res://Sounds/24.wav")
var U25 = preload("res://Sounds/25.wav")
var U26 = preload("res://Sounds/26.wav")
var U27 = preload("res://Sounds/27.wav")
var U28 = preload("res://Sounds/28.wav")
var U29 = preload("res://Sounds/29.wav")
var U30 = preload("res://Sounds/30.wav")
var U31 = preload("res://Sounds/31.wav") # Punch
var U32 = preload("res://Sounds/32.wav")
var U33 = preload("res://Sounds/33.wav")
var U34 = preload("res://Sounds/34.wav")
var U35 = preload("res://Sounds/35.wav")
var U36 = preload("res://Sounds/36.wav")
var U37 = preload("res://Sounds/37.wav")
var U38 = preload("res://Sounds/38.wav")
var U39 = preload("res://Sounds/39.wav")
var U40 = preload("res://Sounds/40.wav")
var U41 = preload("res://Sounds/41.wav")
var U42 = preload("res://Sounds/42.wav")
var U43 = preload("res://Sounds/43.wav")
var U44a = preload("res://Sounds/44a.wav")
var U44b = preload("res://Sounds/44b.wav")
var U45  = preload("res://Sounds/45.wav")
var U46  = preload("res://Sounds/46.wav")
var U47  = preload("res://Sounds/47.wav")
var U48  = preload("res://Sounds/48.wav")
var U49  = preload("res://Sounds/49.wav")
var V00 = preload("res://Sounds/V00.wav") # Punch 1
var V01 = preload("res://Sounds/V01.wav") # Punch 2
var V02 = preload("res://Sounds/V02.wav") # Punch 3
var V03 = preload("res://Sounds/V03.wav") # Punch 4
var V04 = preload("res://Sounds/V04.wav")
var V05 = preload("res://Sounds/V05.wav")
var V06 = preload("res://Sounds/V06.wav")
var V07 = preload("res://Sounds/V07.wav")
var V08 = preload("res://Sounds/V08.wav")
var V09 = preload("res://Sounds/V09.wav")
var V10 = preload("res://Sounds/V10.wav")
var V11 = preload("res://Sounds/V11.wav")
var V12 = preload("res://Sounds/V12.wav")
var V13 = preload("res://Sounds/V13.wav")
var V14 = preload("res://Sounds/V14.wav")
var V15 = preload("res://Sounds/V15.wav")
var V16 = preload("res://Sounds/V16.wav")
var V17 = preload("res://Sounds/V17.wav")
var V18 = preload("res://Sounds/V18.wav")
var V19 = preload("res://Sounds/V19.wav")
var V20 = preload("res://Sounds/V20.wav")
var V21 = preload("res://Sounds/V21.wav")
var V22 = preload("res://Sounds/V22.wav")
var V23 = preload("res://Sounds/V23.wav")
var V24 = preload("res://Sounds/V24.wav")
var V25 = preload("res://Sounds/V25.wav")
var V26 = preload("res://Sounds/V26.wav")
var V27 = preload("res://Sounds/V27.wav")
var V28 = preload("res://Sounds/V28.wav")
var V29 = preload("res://Sounds/V29.wav")
var V30 = preload("res://Sounds/V30.wav")
var V31 = preload("res://Sounds/V31.wav")
var V32 = preload("res://Sounds/V32.wav")
var V33 = preload("res://Sounds/V33.wav")
var V34 = preload("res://Sounds/V34.wav")
var V35 = preload("res://Sounds/V35.wav") # Dead 1
var V36 = preload("res://Sounds/V36.wav")
var V37 = preload("res://Sounds/V37.wav")
var V38 = preload("res://Sounds/V38.wav")
var V39 = preload("res://Sounds/V39.wav")
var V40 = preload("res://Sounds/V40.wav")
var V41 = preload("res://Sounds/V41.wav")
var V42 = preload("res://Sounds/V42.wav")
var V43 = preload("res://Sounds/V43.wav")
var V44 = preload("res://Sounds/V44.wav")
var V45 = preload("res://Sounds/V45.wav")
var V46 = preload("res://Sounds/V46.wav")
var V47 = preload("res://Sounds/V47.wav")
var V48 = preload("res://Sounds/V48.wav")
var V49 = preload("res://Sounds/V49.wav")
var V50 = preload("res://Sounds/V50.wav")
var V51 = preload("res://Sounds/V51.wav")
var V52 = preload("res://Sounds/V52.wav")

#var sound_die        = preload("res://sounds/sfx_die.wav")
#var sound_hit		= preload("res://sounds/sfx_hit.wav")
#var sound_point 	= preload("res://sounds/sfx_point.wav")
#var sound_swooshing = preload("res://sounds/sfx_swooshing.wav")
#var sound_wing 		= preload("res://sounds/sfx_wing.wav")

func play_punch() -> void:
    self.stream = V00
    self.play()
    
func play_punch_air() -> void:
    self.stream = U00
    self.play()
    
func play_dead() -> void:
    self.stream = V35
    self.play()
